extends: ['eslint-config-airbnb-base']

env:
  node: true
  es6: true

rules:
  prefer-arrow-callback:
    - 0
  no-return-assign: 0
  no-use-before-define: off
  prefer-destructuring: 0
  quotes: [2, "single", "avoid-escape"]
  comma-dangle: ["error", "never"]
  no-console: "off"
  no-unused-vars: "off"
  function-paren-newline: "off"
  array-callback-return: "off"
  radix: "off"
  object-curly-newline: "off"
  padded-blocks: "off"
