version: '3'

services:
  postgres:
    image: postgres
    env_file: .env.production

  powermeter:
    command: sleep infinity
    env_file: .env.production
    volumes:
        - .:/home/node/app
    depends_on:
      - postgres
    links:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  powermeter:
