version: '3'

services:
  postgres:
    image: postgres
    env_file: .env.production
    restart: always
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/:ro

  powermeter:
    command: sleep infinity
    env_file: .env.production
    depends_on:
      - postgres
    links:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres:
